# Generated by Django 4.2.4 on 2024-01-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesorden',
            name='unidad',
            field=models.CharField(default='KG', max_length=10),
        ),
    ]
