# Generated by Django 4.2.4 on 2024-01-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0003_orden_compra_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='', max_length=150),
        ),
    ]
